version: '3.4'
services:
  nginx:
   container_name: nginx-container
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
 
  mysql:
    container_name: mysql-container
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
      - MYSQL_DATABASE=persons_register
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    ports:
      - "3306:3306"
  
  app:
    container_name: app-container
    restart: always
    build: ./
    working_dir: /srv/run
    volumes:
      - .:/srv/run
    expose:
      - "8080"
    command: "gradle tasks bootRun"
    depends_on:
      - mysql
